### ISSUE TITLE
onVisibilityChanged is not working as expected

### ISSUE THREAD

**Issue by FatimaJaffal** [HubSpot/calling-extensions-sdk#116]
**Description**
1. We receive `onVisibilityChanged` message with invalid data, for example if the user minimizes the call widget, we receive `data: Object { isMinimized: false, isHidden: false }`, same issue if you send `callCompleted({ hideWidget: true }) `.
2. If the user clicks the `X` button at the top of the call widget, we will not receive `onVisibilityChanged`.

**Expected behavior**
`onVisibilityChanged`  should reflect the correct call widget state.

**To Reproduce**

1. Go to any contact page.
2. Open the call widget.
3. Try to minimize it, you should receive 
```
{
  "type": "VISIBILITY_CHANGED",
  "data": {
    "isMinimized": false,
    "isHidden": false
  },
}
```
4. Try to click the `X` button, you will not receive `onVisibilityChanged` message.

**Comment by esme** [comment]
@FatimaJaffal Thank you for reporting this! We've investigated the issue and will roll out the fix tomorrow. You should see `onVisibilityChanged` message when you click on the `X` button while in a third party app.

**Comment by FatimaJaffal** [comment]
@esme Thank you for the fast response, just to confirm that this will fix the first issue as well?

**Comment by esme** [comment]
@FatimaJaffal Yes this will fix the first issue and return`{ isMinimized: true, isHidden: false }` instead.

I haven't been able to reproduce the bug for the back button. Would you mind testing it again with the revert and seeing if the back button now works?

**Comment by FatimaJaffal** [comment]
@esme Yes, works, thank you!!
