### ISSUE TITLE
Permissions for Notifications are denied after some time

### ISSUE THREAD

**Issue by uso5** [HubSpot/calling-extensions-sdk#155]
**Checklist**
- [X] I have read the [FAQs](https://github.com/HubSpot/calling-extensions-sdk#faqs).
- [X] I have checked the [issue tracker](https://github.com/HubSpot/calling-extensions-sdk/issues) for duplicate issues.

**Description**

When you try to use CTI inside Hubspot after some time Iframe has declined Notification permission (see screenshot). This happens for our app only inside Hubspot environment and we are not able to reproduce it always. This sometimes happens when you reload iframe. 
Maybe question here would be: Is Hubspot somehow disabling permissions for Notifications inside CTI? 

**Expected behavior**

Iframe should have always Notification permission granted. 

**To Reproduce**

1. Go to Hubpost interface 
2. Show CTI 
3. Try to reload iframe 
4. After some time (not always) permissions are denied

**Screenshots/source code**

![Screenshot 2023-11-06 at 09 14 11](https://github.com/HubSpot/calling-extensions-sdk/assets/1119749/a9ada92c-08ac-454c-8a35-145d99fbf815)

**Additional context**

N/A

**Comment by esme** [comment]
Hey @uso5 Thanks for reporting the issue in a new ticket. Will test this in CloudTalk CTI next week and get back to you.

**Comment by esme** [comment]
@uso5 I don't believe we are disabling notifications within the CTI. Does this error only show up after an iframe reload? I have been unable to reproduce it using our Demo Widget.
