### ISSUE TITLE
failed to integrate call widget when redirect

### ISSUE THREAD

**Issue by takahashita35** [HubSpot/calling-extensions-sdk#18]
we’d like our customer to set their own CTI Url on HubSpot, each url begins with their own subdomain, e.g. x1.XXX.jp, v1.XXX.jp. But seems it is not possible to set different CTI Url for each customer on HubSpot, so we decided to set common url as prodctionWidgetURL, and redirect to CTI Url.

It runs as expected on localhost, but won’t run as expected on our testing environment.

We guess that web browser have not send `_Constants.messageType.SYNC` , when host of prodctionWidgetURL and displayed url on iframe are different.

IFrameManager.js
```
key: "onMessage",
    value: function onMessage(event) {
      var data = event.data,
          origin = event.origin;

      if (this.destinationHost !== origin) {
        // Ignore messags from an unkown origin
        return;
      }
```

Could you fix to integrate call widget when redirect?

**Comment by HarminderSingh1** [comment]
You are right that HubSpot won't send the SYNC message again as it currently doesn't listen for iFrame URL change.  When the URL changed, calling extensions will need to re-bootstrap with the new page.  This is a new use case and we'll fix this.

**Comment by HarminderSingh1** [comment]
@takahashita35 - I've updated npm package with a [fix](https://github.com/HubSpot/calling-extensions-sdk/commit/f5b3d06845cc948ead26b805b5c0320c5a3114ba).   Please let me know if this fixes the issue.

**Comment by takahashita35** [comment]
@HarminderSingh1 We were able to launch CTI. But after 30 seconds, the message what indicates loading calling window error appears above the CTI. After another 30 seconds, CTI will disappear and only the error message will be displayed.
Do we need to fix anything?

**Comment by HarminderSingh1** [comment]
@takahashita35 - The error means that HubSpot and the call widget weren't able to communicate within 30 seconds.  Just to confirm - 1) you are on the package v.7 and 2) you are sending the SET_WIDGET_URL message mentioned [here](https://github.com/HubSpot/calling-extensions-sdk/commit/f5b3d06845cc948ead26b805b5c0320c5a3114ba).  If so, I can help debug the issue; could you please send me your widget url and a test account to hsingh at hubspot dot com.

**Comment by takahashita35** [comment]
@HarminderSingh1 We have solved that prolem by sending the SET_WIDGET_URL message and making the following settings.

We were sending the SET_WIDGET_URL message like this.
```
cti.sendMessage({
    type: messageType.SET_WIDGET_URL,
    iFrameUrl: 'https://x1.XXX.jp/phone'
});
```
But the correct message is like this.
```
cti.sendMessage({
    type: messageType.SET_WIDGET_URL,
    iFrameUrl: 'https://x1.XXX.jp'
});
```

Thank you for giving me good advice!

**Comment by takahashita35** [comment]
@HarminderSingh1 There is another problem. We launched CTI using a redirect, but CTI didn't have a microphone permission.
We think that the Feature Policy settings are not correct.

**Comment by HarminderSingh1** [comment]
Hi @takahashita35 - We ask for microphone permission when the iFrame is loaded, but that is tied to the initial URL.  In your case, the iFrame navigates to a url that may not have the microphone permissions.  You can easily request the microphone permissions using [browser API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia).  I don't think there is a way around this.

**Comment by takahashita35** [comment]
@HarminderSingh1 I'm awfully sorry for my late reply. By placing CTI with iframe in the first page, the problem is solved and CTI runs as expected. Thank you!

**Comment by xvlcekp** [comment]
Hi guys, I know this topic is already closed, but I cannot figure out how to do the redirect.
Here is my scenario:
1. I set an initial URL to a decision server. It retrieves the portal ID, makes the API request to get the url.
2. I set 'SET_WIDGET_URL' with the new URL
3. I do the redirect to the new URL. It is very similar to the example above. The URLs are in format: company1.x.com, company2.x.com, company3.x.com and so on...

```
<script>
    let redirectUrl = "getInstance?hubspot_id=";
    const sizeInfo = {
        width: 400,
        height: 650,
    };

    const cti = new window.default({
        debugMode: true,
        eventHandlers: {
            onReady: ({ engagementId, portalId, userId } = {}) => {
                cti.initialized({
                    engagementId,
                    isLoggedIn: false,
                    sizeInfo,
                });
                if (portalId) {
                    fetch(redirectUrl + portalId)
                        .then((response) => response.json())
                        .then((json) => {
                            console.log(json);
                            cti.sendMessage({
                                type: 'SET_WIDGET_URL',
                                iFrameUrl: `https://${json.instance}`
                            });
                            window.location.assign(`https://${json.instance}/custom/ENT/hubspot/web/index.html`);
                        });
                }
            },
        },
    });
</script>
```

In log I am getting just these errors(I removed non-important sensitive data):
![image](https://github.com/user-attachments/assets/f28b31e9-8355-4c2a-b6ce-aa874311c6ab)

Thank you very much for help.

P.S: It works, when the initial URL is set to the same domain as the final domain, e.g. company1.x.com. The problem is that at the beginning I don't know which domain should be set, because it is retrieved based on the portal ID.
