### ISSUE TITLE
Limit calling-minutes-per-portal could not be found for portalId

### ISSUE THREAD

**Issue by danj1980** [HubSpot/calling-extensions-sdk#204]
**Checklist**
- [✔️] I have read the [FAQs](https://github.com/HubSpot/calling-extensions-sdk#faqs).
- [✔️] I have checked the [issue tracker](https://github.com/HubSpot/calling-extensions-sdk/issues) for duplicate issues.

**Description**
In LIVE mode, when the user presses the Phone icon in the toolbar, they receive the following notification.
![DanJ_0-1716207333332](https://github.com/HubSpot/calling-extensions-sdk/assets/12071228/a52d36f4-772b-4876-98ac-800fce617932)
The HubSpot HTTP response when that button is pressed says 
> [portalId: 144XXXXXX] Limit calling-minutes-per-portal could not be found for portalId

However, the app is connected successfully as the user is able to press the Call icon directly on a Contact. It is simply that they cannot open the widget via the Phone icon in the toolbar.

In Local mode, the app functions perfectly and the Phone icon in the toolbar functions correctly.

**Expected behavior**
In LIVE mode, the phone icon should open the third party calling widget.

**To Reproduce**
1. Install a third party calling integration that uses the Calling Extensions SDK.
2. Press the Phone icon in the toolbar.
3. See the response says that you do not have access.

**Screenshots/source code**
Screenshot showing what happens when the Phone icon is pressed
![DanJ_0-1716207333332](https://github.com/HubSpot/calling-extensions-sdk/assets/12071228/33637d11-abd7-48e0-9d5c-d86b1e69cfee)
Contact showing that the integration and third party calling is available
![DanJ_1-1716207412484](https://github.com/HubSpot/calling-extensions-sdk/assets/12071228/d3a7bae6-b02b-4385-bb60-b4a0850e33f6)

**Device information**
Device: PC
OS: Windows 11
Browser: Tested with the latest versions of Firefox, Chrome and Edge

**Comment by hemang-thakkar** [comment]
Hello danj1980

Thank you for reaching out. By LIVE mode, I assume you mean that you are using the actual calling app and not the one served from the local server.

Can you try this? https://developers.hubspot.com/docs/api/crm/extensions/receive-calls-in-hubspot-when-using-calling-apps#ungate-your-account

Let us know if you still see the issue.

Thank you

Hemang Thakkar

**Comment by danj1980** [comment]
It appears that the option is not available on Free accounts which is probably incorrect?
![image](https://github.com/HubSpot/calling-extensions-sdk/assets/12071228/214f651f-05c3-4c99-9008-195a3507eade)

**Comment by danj1980** [comment]
Please also see here where the comment says that it is a Hubspot system issue?
https://community.hubspot.com/t5/APIs-Integrations/Limit-calling-minutes-per-portal-could-not-be-found-for-portalId/m-p/982611/highlight/true#M73936

**Comment by hemang-thakkar** [comment]
Hello @danj1980 I tried to reproduce the issue on our end but I couldn't. Can you still reproduce it? Here's what I see.
![image](https://github.com/HubSpot/calling-extensions-sdk/assets/59508898/f33d52d4-4440-4282-ad59-b713418727b2)

Can you see an option to select Calling Provider on settings page? like this
![image](https://github.com/HubSpot/calling-extensions-sdk/assets/59508898/d5bcff1a-f768-407d-aa70-a43efc8ed054)

If yes, then select your provider and then you should be able to see the calling app in the popover.

**Comment by hemang-thakkar** [comment]
Can you confirm if 'isReady' set to true? If 'isReady' is set to false and if it's only integration installed in your portal, then you would not see the calling provider dropdown.

cc @alonso-cadenas

**Comment by hemang-thakkar** [comment]
@danj1980 Do you have any more questions? If not, then we would go ahead and close this issue. In case issue persists, you can reopen the issue.

Hemang Thakkar
