### ISSUE TITLE
onDialNumber is getting called twice on click to call trigger on a contact

### ISSUE THREAD

**Issue by sehgalhimanshusparktg** [HubSpot/calling-extensions-sdk#210]
I am using the demo react app to create an integration. I just noticed that the onDialNumber event is getting called 2 times. Can anybody check why could be so ?
![image](https://github.com/user-attachments/assets/ec7bb1ad-eea4-4e23-864d-65ab44236104)

**Comment by alonso-cadenas** [comment]
Hi, @sehgalhimanshusparktg! Thank you for reporting the issue. We're currently working on a fix.

**Comment by alonso-cadenas** [comment]
Hi, @sehgalhimanshusparktg! We've addressed this issue. Please let us know if you experience otherwise!

Best regards,
Alonso
