### ISSUE TITLE
Invalid objectId onDialedNumber callback

### ISSUE THREAD

**Issue by murugancmi** [HubSpot/calling-extensions-sdk#216]
**Checklist**
- [x] I have read the [FAQs](https://github.com/HubSpot/calling-extensions-sdk#faqs).
- [x] I have checked the [issue tracker](https://github.com/HubSpot/calling-extensions-sdk/issues) for duplicate issues.

**Description**
When we click the call button from contact, We receive the contact Object onDialNumber but it contains in 0 in objectId 

**Expected behaviour**
Contact object should contain objectId

**To Reproduce**

1. Go to your contact
2. and click the call button

**Screenshots/source code**
{
 phoneNumber: 'xxxx',
 phone_number: 'xxxx,
 countryCode: 'IN',
 calleeInfo: { calleeId: 120513766, calleeObjectTypeId: '0-1' },
 ownerId: 295128649,
 subjectId: 0,
 objectId: 0,
 startTimestamp: 1723291227334,
 portalId: 81431,
 toPhoneNumberSrc: 'phone',
 threadId: 0
}

**Device information**

Device: Mac book pro
OS: macOS Sonam 14.5
Browser: [chrome]
Browser Version: [126.0.6478]

**Comment by alonso-cadenas** [comment]
@esme, thank you for digging into this. I've submitted a second request to our technical writers so we can update the documentation.

@murugancmi, apologies for any inconvenience!

**Comment by prasathsekar** [comment]
@esme Thank you for the earlier response regarding retrieving contact info from calleeInfo. We've implemented the suggested changes, but we’re facing an issue when dialing contacts mapped to companies.

When calling a contact associated with a company, the objectId and calleeId differ, which are unable to post the call log.


![Screenshot 1](https://github.com/user-attachments/assets/621ab367-0bc2-455a-b012-8aac7247d315)



![Uploading Screenshot 2.png…]()

**Comment by prasathsekar** [comment]
@esme Thank you for the earlier response regarding retrieving contact info from calleeInfo. We've implemented the suggested changes, but we’re facing an issue when dialing contacts mapped to companies.

When calling a contact associated with a company, the objectId and calleeId differ, which are unable to post the call log.

![Screenshot 1](https://github.com/user-attachments/assets/638aab13-1126-4802-a3ac-a4ae070bc95c)

![Screenshot 2](https://github.com/user-attachments/assets/2eaf44cb-c4ab-4256-9d5f-aaa6ca2e262f)
