### ISSUE TITLE
SDK & Angular or React integration

### ISSUE THREAD

**Issue by habibmevlut** [HubSpot/calling-extensions-sdk#220]
Hello everyone,

We have started actively using the HubSpot application at our nonprofit organization in Turkey, and we are very satisfied with it. In our current system, we manage Call Center operations through Netgsm(https://www.netgsm.com.tr/). However, to make this process more efficient, we would like to implement a HubSpot + SDK integration. We are considering using Angular for the frontend, but we could also proceed with React, as seen in the demo examples.

There are some points in the implementation process that are unclear, and we have some gaps. Could we get support from you on this matter? We wanted to reach out to you here following @hemang-thakkar 's  suggestion.

**Comment by alonso-cadenas** [comment]
Hi @habibmevlut, we appreciate your efforts to integrate with HubSpot! These GitHub issues and bugs are used to improve the calling-extensions-sdk and its demo apps. To receive dedicated support with your app, please join our [App Partner Program](https://www.hubspot.com/partners/app).

Best regards,
Alonso
