### ISSUE TITLE
SET_WIDGET_URL doesn't work 

### ISSUE THREAD

**Issue by xvlcekp** [HubSpot/calling-extensions-sdk#229]
I cannot figure out how to do the redirect.
Here is my scenario:
1. I set an initial URL to a decision server. It retrieves the portal ID, makes the API request to get the url.
2. I set 'SET_WIDGET_URL' with the new URL
3. I do the redirect to the new URL. It is very similar to the example above. The URLs are in format: company1.x.com, company2.x.com, company3.x.com and so on...

```
<script>
    let redirectUrl = "getInstance?hubspot_id=";
    const sizeInfo = {
        width: 400,
        height: 650,
    };

    const cti = new window.default({
        debugMode: true,
        eventHandlers: {
            onReady: ({ engagementId, portalId, userId } = {}) => {
                cti.initialized({
                    engagementId,
                    isLoggedIn: false,
                    sizeInfo,
                });
                if (portalId) {
                    fetch(redirectUrl + portalId)
                        .then((response) => response.json())
                        .then((json) => {
                            console.log(json);
                            cti.sendMessage({
                                type: 'SET_WIDGET_URL',
                                iFrameUrl: `https://${json.instance}`
                            });
                            window.location.assign(`https://${json.instance}/custom/ENT/hubspot/web/index.html`);
                        });
                }
            },
        },
    });
</script>
```

In log I am getting just these errors(I removed non-important sensitive data):
![image](https://github.com/user-attachments/assets/f28b31e9-8355-4c2a-b6ce-aa874311c6ab)

Thank you very much for help.

P.S: It works, when the initial URL is set to the same domain as the final domain, e.g. company1.x.com. The problem is that at the beginning I don't know which domain should be set, because it is retrieved based on the portal ID.

_Originally posted by @xvlcekp in https://github.com/HubSpot/calling-extensions-sdk/issues/18#issuecomment-2363876419_

**Comment by alonso-cadenas** [comment]
Hi @xvlcekp, we appreciate your efforts to integrate with HubSpot! These GitHub issues are used to improve the calling-extensions-sdk and its demo apps. If this is a feature request or a bug, please fill out our templates. Otherwise, to receive dedicated support with your app, please join our [App Partner Program](https://www.hubspot.com/partners/app).

Best regards,
Alonso
