### ISSUE TITLE
Calling SET_WIDGET_URL doesn't work before redirect to other URL

### ISSUE THREAD

**Issue by xvlcekp** [HubSpot/calling-extensions-sdk#230]
**Checklist**
- [x] I have read the [FAQs](https://github.com/HubSpot/calling-extensions-sdk#faqs).
- [x] I have checked the [issue tracker](https://github.com/HubSpot/calling-extensions-sdk/issues) for duplicate issues.

**Description**
I cannot figure how to redirect to a different widget URL. I assume send message of type 'SET_WIDGET_URL' doesn't work.
Here is my scenario:

I set an initial URL pointing to a decision server. It retrieves the portal ID, makes the API request to get the customer's url.
Before redirect, I set 'SET_WIDGET_URL' with the new URL
I do the redirect to the new URL. It is very similar to the issue [#18](https://github.com/HubSpot/calling-extensions-sdk/issues/18) . The URLs are in format: company1.x.com, company2.x.com, company3.x.com and so on...

**Expected behavior**
When I send a message of type **messageType.SET_WIDGET_URL**, I expect the iFrameManager stores the new host, so I can do the redirect to this URL, where a **calling-extensions-sdk** library will be initialized.

**To Reproduce**
I am calling this message, but it has no effect:
```
      cti.sendMessage({
          type: 'SET_WIDGET_URL',
          iFrameUrl: `https://newInstance.host.com/custom//index.html`
      });
```

**Screenshots/source code**
```
<script>
    const sizeInfo = {
        width: 400,
        height: 650,
    };
    const cti = new window.default({
        debugMode: true,
        eventHandlers: {
            onReady: ({ engagementId, portalId, userId } = {}) => {
                cti.initialized({ // The script was initialized to get portalId
                    engagementId,
                    isLoggedIn: false,
                    sizeInfo,
                });
                if (portalId) {
                    let newUrl = getUrlPlaceholder(); // We fetch URL based on portalId
                    cti.sendMessage({
                        type: 'SET_WIDGET_URL',
                        iFrameUrl: `https://${newUrl}`
                    });
                    window.location.assign(`https://${newUrl}/custom/index.html`); // I assume this script will initialize the library after redirect
                }
            },
        },
    });
</script>
```
![hubspot cti panel](https://github.com/user-attachments/assets/c1ab20df-10fe-462f-aa91-6e3cf5e681b1)

**Device information**
https://www.whatsmybrowser.org/b/UCQLI

**Additional context**
I cleared the private information because of data protection. If you need further information, let me know.

**Comment by esme** [comment]
Hi @xvlcekp, the iframeManager indeed doesn’t persist the URL across window unload events. Instead of using SET_WIDGET_URL to store the new URL before redirecting, you might consider using local storage or session storage to save the URL. This way, you can retrieve it after the redirect and call SET_WIDGET_URL to initialize the sdk library as needed. Let me know if this answers your question!

**Comment by Esirei** [comment]
> Hi @xvlcekp, the iframeManager indeed doesn’t persist the URL across window unload events. Instead of using SET_WIDGET_URL to store the new URL before redirecting, you might consider using local storage or session storage to save the URL. This way, you can retrieve it after the redirect and call SET_WIDGET_URL to initialize the sdk library as needed. Let me know if this answers your question!

I'm having the same issues reported here.
Unfortunately, this solution does not work on the new page as the calling extension has not been initialised.

**Comment by xvlcekp** [comment]
Hi @esme thanks for your answer. The problem isn't with storing the URL, but once the iframeManager is initialized with one domain, it doesn't initialize on the other again. Setting [new destinationHost](https://github.com/HubSpot/calling-extensions-sdk/blob/master/src/IFrameManager.js#L268 ) is required. On the new domain it is not possible to do anyting as @Esirei mentioned, because the communication is [dead](https://github.com/HubSpot/calling-extensions-sdk/blob/master/src/IFrameManager.js#L204).

**Comment by esme** [comment]
@xvlcekp Thanks for the explanation! I don't believe we're ever setting a new destinationHost on `cti.sendMessage({ type: 'SET_WIDGET_URL' })` because this sends the message to our internal SDK support library and we're not handling the message internally. Let me investigate this a little further to figure out we can resolve this

**Comment by esme** [comment]
@xvlcekp @Esirei I have updated the logic to set a new destinationHost on the `SET_WIDGET_URL` event and re-initialize the SDK. Please update your npm package to [0.7.1-alpha.0](https://www.npmjs.com/package/@hubspot/calling-extensions-sdk/v/0.7.1-alpha.0) and use the CTI method on the iframeUrl like this. [Example in demo minimal js widget](https://github.com/HubSpot/calling-extensions-sdk/blob/master/demos/demo-minimal-js/index.js#L167).

Let me know if this fixes the issue for you.

```
cti.setWidgetUrl({ iFrameUrl })
```

**Comment by Esirei** [comment]
> @xvlcekp @Esirei I have updated the logic to set a new destinationHost on the `SET_WIDGET_URL` event and re-initialize the SDK. Please update your npm package to [0.7.1-alpha.0](https://www.npmjs.com/package/@hubspot/calling-extensions-sdk/v/0.7.1-alpha.0) and use the CTI method on the iframeUrl like this. [Example in demo minimal js widget](https://github.com/HubSpot/calling-extensions-sdk/blob/master/demos/demo-minimal-js/index.js#L167).
> 
> Let me know if this fixes the issue for you.
> 
> ```
> cti.setWidgetUrl({ iFrameUrl })
> ```

Thanks for the update @esme. I'll check it out as soon as possible.

**Comment by xvlcekp** [comment]
Thanks for the update @esme 
I tried it yesterday, and unfortunately it does not work as excepted.
1 - entry point
2 - iFrameUrl after redirect
Improvements:
I don't have to redirect to the iFrameUrl manually like: 
`window.location.assign(....` , but instead of that calling 
`cti.setWidgetUrl({ iFrameUrl })` does the redirect automatically.
Unfortunately, the new library on the iFrameUrl is not initialized just like before - it does not communicate.
![image](https://github.com/user-attachments/assets/e7ca2d7b-c223-44db-a499-aea8197fb5dc)

**Comment by esme** [comment]
Hi @xvlcekp,

Are you running your app locally in the HubSpot calling widget iframe? You would have to do so to communicate with the library. For example, I am able to send `USER_AVAILABLE` and `INCOMING_CALL` messages after setting the widget's url.

<img width="1459" alt="image" src="https://github.com/user-attachments/assets/a79cd631-c844-4272-a1aa-996216f6bfc5">

**Comment by xvlcekp** [comment]
Hello @esme, thanks very much for help.

When I run it locally, it works, because of the same domain (localhost). It works even on the same domain, 
e.g: `test.com/entry-point -> test.com/customersId`.
When I test it under real circumstances, e.g: `test.com/entry-point -> customer.com/ctiPanel ` the widget on the new URL doesn't initialize the library. Is it possible for you to simulate it using different destinationURL? Thanks

**Comment by esme** [comment]
@xvlcekp I am able to reproduce the issue with a different domain and have pushed a fix to send messages to the new destinationUrl. Will update you once the fix is in PROD - thank you for your patience!

**Comment by esme** [comment]
@xvlcekp I believe the fix is now in PROD. Mind testing again to see if it works on a new domain for you?

**Comment by Esirei** [comment]
> @xvlcekp I believe the fix is now in PROD. Mind testing again to see if it works on a new domain for you?

It works! Thank you for the quick rectification @esme.
