### ISSUE TITLE
onDialNumber doesn't have objectId

### ISSUE THREAD

**Issue by ivanchenko** [HubSpot/calling-extensions-sdk#232]
Sorry for reopening same issue, but your support team didn't reach out with me and I don't have another ways to contact you. This issue is still persists in my app.

Hi @ivanchenko, we'll need your customers to reach out to HubSpot support directly in order to resolve the issue. Given that the issue is happening 20-30 times a day, we can try a few ways to troubleshoot.

Thank you for integrating with HubSpot!

Best regards,
Alonso

_Originally posted by @alonso-cadenas in https://github.com/HubSpot/calling-extensions-sdk/issues/228#issuecomment-2361284955_

**Comment by alonso-cadenas** [comment]
@ivanchenko No problem at all. I've reopened the original issue so we can continue the conversation there. In addition, I've confirmed that our support team has responded to your support request. I'm currently investigating the issue.
