### ISSUE TITLE
Hubspot ID

### ISSUE THREAD

**Issue by ilushka85** [HubSpot/calling-extensions-sdk#31]
How can our widget obtain the hubspot instance id?

**Comment by HarminderSingh1** [comment]
Hi Ilya - what do you mean by "hubspot instance id?".  Are you referring to the HubSpot Portal Id.
Also, please explain the issue you are solving; we can help identify a solution.

**Comment by ilushka85** [comment]
Yes how do we get the portal id?

**Comment by ilushka85** [comment]
Following up

**Comment by dstgermain** [comment]
Hi @ilushka85, we don't currently send that information. What's the use case you're looking to solve by obtaining the `portalId`?

**Comment by ilushka85** [comment]
Let’s say our extension is installed on two different deployments of hubspot. How do we know which one the user is calling from ?

Kind regards,
Ilya Beyrak | Founder & CEO
Resultly LLC.
(p) 312.273.9401
(m) 847.912.1212
(w) www.result.ly ( http://www.result.ly/ )

Sent via Superhuman iOS ( https://sprh.mn/?vip=ilya@resultly.com )

**Comment by dstgermain** [comment]
I'll double check that this is ok to send and put a note here when it's done.

**Comment by dstgermain** [comment]
All set, this is in Prod and added to the Docs.

**Comment by ilushka85** [comment]
Thank you

**Comment by zoell** [comment]
@dstgermain what would be the correct way to get the portalId during initialization so we can decide where to redirect the iframe using [this fix](https://github.com/HubSpot/calling-extensions-sdk/commit/f5b3d06845cc948ead26b805b5c0320c5a3114ba)?
