### ISSUE TITLE
Additional user information

### ISSUE THREAD

**Issue by v-Andreev** [HubSpot/calling-extensions-sdk#32]
orDinal Number we get information about users, such as phone number, ownerId, etc. Is there a way to get information firstName, lastName, etc.
Maybe there is a way using ownerId or something else?

**Comment by dstgermain** [comment]
ownerId is a number associated with the agent. ObjectId / ObjectType is a reference for the contact or company however, we current don't send their first/last in the data. See: https://github.com/HubSpot/calling-extensions-sdk#receiving-messages-from-hubspot

**Comment by v-Andreev** [comment]
Thanks
