### ISSUE TITLE
Remove default hubspot call provider

### ISSUE THREAD

**Issue by ilushka85** [HubSpot/calling-extensions-sdk#33]
How do we remove the default hubspot phone provider when using our own provider.   This is too confusing to our users that they need to choose our provider.

**Comment by ilushka85** [comment]
Anyone awake here ?

**Comment by dstgermain** [comment]
There's no functionality in place to completely remove the HubSpot provider. Once they select a provider it should persist in localStorage, so they shouldn't have to continuously switch. Maybe down the road we can add something that toggles individual call providers on and off.

**Comment by ilushka85** [comment]
This is highly necessary as we absolutely need our users to use our provider but asking them to choose and ensure their choice hasn’t changed is a major struggle.

Kind regards,
Ilya Beyrak | Founder & CEO
Resultly LLC.
(p) 312.273.9401
(m) 847.912.1212
(w) www.result.ly ( http://www.result.ly/ )

Sent via Superhuman iOS ( https://sprh.mn/?vip=ilya@resultly.com )

**Comment by dstgermain** [comment]
There's something we're working on that will take care of this.

**Comment by ilushka85** [comment]
Any updates on what you are working on that would take care of this?

**Comment by ilushka85** [comment]
Following up on this again

**Comment by MarwaAbuEssa** [comment]
any updates about this ?

**Comment by dstgermain** [comment]
Hi @ilushka85 & @MarwaAbuEssa ,
We don't have a single page app so we have to deal with navigation and currently the call widget is embedded in the current page. We're actively working towards a solution as part of a larger effort, however no immediate updates quite yet.

**Comment by ilushka85** [comment]
@dstgermain can you provide any update on timelines for this?  Specifically the issue mentioned here to remove default HubSpot provider and more importantly a way to handle inbound calling?  We really would like to pop open our widget automatically.

**Comment by FatimaJaffal** [comment]
Any updates on this ?

**Comment by FatimaJaffal** [comment]
Any updates on this?

**Comment by dstgermain** [comment]
@FatimaJaffal - none at the moment. It is on our timeline though, just hasn't gotten to the top of our list yet.

**Comment by dstgermain** [comment]
This is now possible by disabling HubSpot calling in settings > objects > activities
