### ISSUE TITLE
not working on nodejs v 14

### ISSUE THREAD

**Issue by MarwaAbuEssa** [HubSpot/calling-extensions-sdk#37]
Hi ,

I'm trying to use your project with nodejs 14  but it is not generating nodemodules in proper way and running npm start gives error 

`npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.5.0","npm":"6.14.5"})`

Kindly i need your reply as soon as possible because our development team needs a decision  for integration with hub spot

Regards ,
Marwa

**Comment by dstgermain** [comment]
Hi @MarwaAbuEssa, I'll look into this shortly.

**Comment by dstgermain** [comment]
Need more information on this. Are you running the demo project? I'm on node 14 and everything seems ok running that. The files your project will use don't have dependencies outside what you see in the src folder. Running the project however has some dev dependencies.

**Comment by dstgermain** [comment]
The demo project itself looks like this:
![Screen Shot 2020-09-03 at 12 46 47 PM](https://user-images.githubusercontent.com/3300692/92143658-93b9ae00-ede3-11ea-82d6-2e835d7da38c.png)

it's usually run on localhost ex `https://localhost:9025/` where port could change. check the output of `npm run` for a line with `(webpack)-dev-server/client?https://localhost:` in it.

**Comment by MarwaAbuEssa** [comment]
Hi @dstgermain 
Thanks a lot for your reply . I had many trials to run the project on nodejs v14 , it worked only when running command with —force “npm start —force “!

Now I need to add a routing to listen to external webhook .(ex:we had our custom service and on certain event it will send a data object to your calling extension ) so my question is where can I define the routing that receives data object and display it at calling extension iframe ???

Waiting for your reply 

Thanks in advance ,
Marwa

**Comment by dstgermain** [comment]
The demo project is specific to running inside the HubSpot CRM. There's directions on how to do this in the Readme https://github.com/hubspot/calling-extensions-sdk#launchthe-demo-widget-from-hubspot.

If I understand correctly you want to send data to the demo widget from a webhook on your end? That could be done a number of ways however this project just serves as a communication layer between a host page and your calling application (Basically just notifying HubSpot of status changes and receiving callee information from the CRM), so there's no sense of "routing" in the demo or the sdk itself.

**Comment by MarwaAbuEssa** [comment]
hi @dstgermain 

Thanks for your reply . can you give me some hints about those ways you mentioned to send our data to demo widget ?

Regards ,
Marwa

**Comment by MarwaAbuEssa** [comment]
Thanks @dstgermain  I found a way to do so
