### ISSUE TITLE
open/maximize calling iframe

### ISSUE THREAD

**Issue by MarwaAbuEssa** [HubSpot/calling-extensions-sdk#38]
Hi ,

is there a way to control minimize /maximize or open the calling iframe  from js?

Regards ,
Marwa

**Comment by dstgermain** [comment]
Hi Marwa,

There's currently no way to open the widget from this SDK. the user would open the widget themselves by clicking on a number in the CRM or by clicking on the phone icon in the profile sidebar. The only option to toggle close or keep open is in the `hideWidget` param in the `callCompleted` method. That's defaulted to true, however you can keep the widget open by passing false.

Out out curiosity what's the use case for opening the call widget when the user didn't interact with a number?

**Comment by MarwaAbuEssa** [comment]
Hi @dstgermain ,

Thanks for your reply. The case is for the incoming calls as our service on a certain event will start a call and I need to open the iframe widget to display the call data to the CRM agent.

Can I ask if possible to use the same function that exists when the user clicks the phone icon on the sidebar? i.e. when our service event fires an incoming call, the same function of clicking the phone number icon fires ??

Regrads ,
Marwa

**Comment by dstgermain** [comment]
We don't currently fully support inbound calls for a few reasons (Navigation is not prevented, Users could miss calls during navigation). That being said you can use the method `incomingCall` found here: https://github.com/HubSpot/calling-extensions-sdk/blob/master/src/CallingExtensions.js#L42. This will launch the widget.
