### ISSUE TITLE
V2 of the SDK

### ISSUE THREAD

**Issue by Teleplandk** [HubSpot/calling-extensions-sdk#41]
Hi @dstgermain,
We well start using the SDK next week, and plan to develop on the integration while using it.
Do you have any timeline for a V2 of the SDK?
Will there be any breaking changes in V2?
----
...Currently we're working on a larger effort for calling navigation and potentially a V2 of this SDK.

_Originally posted by @dstgermain in https://github.com/HubSpot/calling-extensions-sdk/issues/33#issuecomment-686514939_

**Comment by dstgermain** [comment]
Hi @Teleplandk,
V2 is currently something we are planning out. There will be some breaking changes to harden the APIs and make things easier for us and for integrators to debug. All in all it shouldn't be extremely difficult to update to V2.
