### ISSUE TITLE
Iframe position and passing custom properties from hub spot to calling sdk

### ISSUE THREAD

**Issue by GhazanfarKhan** [HubSpot/calling-extensions-sdk#43]
Hi, Do you any settings to change iframe position, header changes ? Can we pass any custom properties to event like current logged in user etc or any data from hubspot?

**Comment by bent0b0x** [comment]
Hi @GhazanfarKhan! 

Regarding settings for the iframe position/header changes, we do not currently support that in our SDK. Could you let me know a bit more detail about what kinds of things you may want to do if these sorts of settings were made available? This is functionality we could consider depending on the use cases.

As for custom properties in events, do you mean in the events that HubSpot sends to your iframed application? I don't believe we support that at the moment either but I can see how it would be useful. In addition to the logged in user, do you have thoughts as to other pieces of information that you may want?

**Comment by GhazanfarKhan** [comment]
Hi @bent0b0x 

Information such as like portal Id, owner id should be provided on ready event so that we can initialize and do some auth related stuff to our app. And for iframe position how can we make it movable within the screen.

**Comment by bent0b0x** [comment]
@GhazanfarKhan thank you for the additional information. 

Apologies again that we do not support either of these features right now, but I will document these requests internally and discuss with my team to see if this is something we can prioritize

**Comment by FatimaJaffal** [comment]
Hello @bent0b0x, any updates on this?

**Comment by dstgermain** [comment]
1. For iframe position how can we make it movable within the screen.
- This is a feature in our V2 experience that is currently being released. It's not controllable by the third party integration directly, I'd like to understand more about the use case for that.
2. I'll look at prioritizing the portalId & ownerId additions. I'll probably get to it next week and will confirm here when it's done.

**Comment by FatimaJaffal** [comment]
@dstgermain, any ETA to release it? Also does v2 support inbound calls?

**Comment by dstgermain** [comment]
Hi @FatimaJaffal,

Sorry for the hold up, I'll look at this today. There are plans to enable inbound calling in the future, but we don't have a hardened timeline at the moment for that feature.

**Comment by dstgermain** [comment]
@FatimaJaffal, this information is available in the `onDialNumber` data. The following attributes are on the object that is passed through the SDK:
```
ownerId: 123,
portalId: 456
```
Is this not what you're looking for?

**Comment by dstgermain** [comment]
Closing this out
