### ISSUE TITLE
New update issues

### ISSUE THREAD

**Issue by pravnyadv** [HubSpot/calling-extensions-sdk#45]
since new update to calls feature I am facing few issues:

1. - callCompleted doesn't close the call iframe
2. - Testing your app from a local environment ( setting new local app url from localstorage doesn't work)

Description 1: after call is ended i am calling `cti.callCompleted(engagementData)` it used to close the call iframe before the update but it doesn't close anymore.

Description 2: i tried (https://github.com/HubSpot/calling-extensions-sdk#testing-your-app-from-a-local-environment) but not able to see the demo app in provider's list.

any help or reply would be appreciated.
thanks

**Comment by FatimaJaffal** [comment]
Also `onVisibilityChanged` is not trigger anymore.

**Comment by dstgermain** [comment]
@pravnyadv 
1 - We'll look into this
2 - Instead of `LocalSettings:Sales:CallingExtensions` please use `LocalSettings:Calling:CallingExtensions`
@FatimaJaffal 
I'll look into onVisibilityChanged

**Comment by dstgermain** [comment]
@pravnyadv + @FatimaJaffal 
The fix for these events will be out shortly.

**Comment by dstgermain** [comment]
The fixes should be out, also I've added the original storage setting key back in as a back up. Closing out for now, please reopen or create another issue if anything else comes up.
