### ISSUE TITLE
In some situation, would created some ghost call logs

### ISSUE THREAD

**Issue by zxdong262** [HubSpot/calling-extensions-sdk#46]
```js
// Sends a message to notify HubSpot that an outgoing call has started.

const callInfo = {
  phoneNumber: string, // optional unless call is initiated by the widget
  createEngagement: true // whether HubSpot should create an engagement for this call
};
extensions.outgoingCall(callInfo);
```

This engagement do not have a status of "completed", normally when call end, will update this call engagement as "completed", it will appear in timeline.
```js
// Sends a message to notify HubSpot that the call has completed.
// After receiving the call completed event, HubSpot will
//   1) insert the engagement into the timeline
//   2) set the default associations on the engagement
//   3) closes the the widget unless `hideWidget` is set to false.
const data = {
  engagementId: number,
  hideWidget: boolean // (optional) defaults to true
};
extensions.callCompleted(data);
```

But in some situations, somehow failed to call `extensions.callCompleted(data)`, then this will create a ghost call log in timeline, the behavior would when goto this page, would some call log slot loading, but after page loaded, the call log slots disappear, if check requests from browser developer tool, would see engagements data like this:
<img width="1409" alt="Screen Shot 2021-03-10 at 6 53 22 PM" src="https://user-images.githubusercontent.com/1641949/111489256-ed2c6d80-8774-11eb-991a-ba4074fb8cb5.png">

**Comment by dstgermain** [comment]
Hi @zxdong262 
I see you're using `callEngagement: true` to create the initial engagement. We expect your widget to then update the call status to `COMPLETED` via the [engagement api](https://legacydocs.hubspot.com/docs/methods/engagements/update_engagement-patch). Passing the `engagementId` through `callCompleted` only enables us to add the engagement to the timeline.

**Comment by zxdong262** [comment]
@dstgermain Normally or in most cases it works as expected, in some rare situation like a power shutdown or maybe network issue, this could happen, got complains about the call log showed and disappeared.

**Comment by dstgermain** [comment]
@zxdong262 So your is app updating that status and for whatever reason sometimes it's missing, however, you're getting 200s from the API?

**Comment by zxdong262** [comment]
@dstgermain I mean the update status request may not be sent for some reason, like network issue, reload the page, or shutdown, or some situation we do not know. anyway, it already happened, like the saying that ```if something could happen, it will happen```, could HubSpot clear this kind of ghost call logs? that's the customer needed.

**Comment by dstgermain** [comment]
I understand the situation, let me check in with our team and see if this is a possibility.

**Comment by dstgermain** [comment]
@zxdong262 - apologies for the delay. We don't have any infrastructure for this however you should be able to handle this on your end. If network is down for some reason and you have this case where engagements are stuck in IN_PROGRESS. you could have a nightly job on your end that cleans those up and converts them to a COMPLETED status. We don't have a way of doing this on our side because we don't want to accidentally convert statuses for third parties that don't want this functionality or have jobs on their end to update the status.

**Comment by zxdong262** [comment]
> @zxdong262 - apologies for the delay. We don't have any infrastructure for this however you should be able to handle this on your end. If network is down for some reason and you have this case where engagements are stuck in IN_PROGRESS. you could have a nightly job on your end that cleans those up and converts them to a COMPLETED status. We don't have a way of doing this on our side because we don't want to accidentally convert statuses for third parties that don't want this functionality or have jobs on their end to update the status.

@dstgermain 

When `createEngagement: true`, the engagement is created by HubSpot, not by third party call provider, before third party can update it once, have no data of this engagement, so it can only be handled by HubSpot?

```
// Sends a message to notify HubSpot that an outgoing call has started.

const callInfo = {
  phoneNumber: string, // optional unless call is initiated by the widget
  createEngagement: true // whether HubSpot should create an engagement for this call
};
extensions.outgoingCall(callInfo);
```
