### ISSUE TITLE
Issue with the floating widget

### ISSUE THREAD

**Issue by FatimaJaffal** [HubSpot/calling-extensions-sdk#49]
Can we get a message indicating that the user has clicked the back button in the floating widget?

**Comment by dstgermain** [comment]
@FatimaJaffal We have an item for this internally. It will respond as hidden when the user clicks the back button. We'll let you know when it's out.

**Comment by FatimaJaffal** [comment]
@dstgermain Any update on this?

**Comment by dstgermain** [comment]
Apologies for the delay the fix is out.
