### ISSUE TITLE
Incoming call support

### ISSUE THREAD

**Issue by honkimi** [HubSpot/calling-extensions-sdk#55]
I know you are trying to support incoming call by HubSpot. (not iframe)
https://community.hubspot.com/t5/HubSpot-Ideas/Handle-inbound-incoming-calls-in-HubSpot/idi-p/14232

I want to provide iframe incoming call  using calling-extensions-sdk.
But,,, this project looks completely stopped..

Should I give up using HubSpot iframe incoming call?

**Comment by dstgermain** [comment]
Apologies for the delay here, We never actually fully supported inbound calling in this project. We're currently talking though a version 2 of this project that will add inbound functionalities.

**Comment by honkimi** [comment]
Thanks, I can't wait to see v2.
