### ISSUE TITLE
Include ownerId in "onReady" event data

### ISSUE THREAD

**Issue by ghost** [HubSpot/calling-extensions-sdk#56]
Hi, guys

We are building a CTI integration with Hubspot on top of our current integration features, and we're having an issue we'd like to ask your help with, if possible.

Currently, the current agent/user's ID (ownerId) is only sent on the `onDialNumber` event, and we'd like to ask if you could also send that data on the `onReady` event, because that's when we're initializing our CTI and prompting the user for login, etc.

Is this possible?
Thanks!

**Comment by alonso-cadenas** [comment]
It looks like the requester has deleted their account, but adding context in case more interest arises. First off, apologies for the delay. This repo was only being monitored for critical bugs. However, we are now starting to actively work on it and closely monitoring open issues. We will be releasing a new version of the SDK later this year that includes a change to the events and their contract. We'll keep this request in mind!
