### ISSUE TITLE
problems with the demo

### ISSUE THREAD

**Issue by andersiversen** [HubSpot/calling-extensions-sdk#8]
When running `npm i` it fails because webpack cannot find an entry file it tries to look at default ./src, which isn't there:
```
user@server /some/path/node_modules/@hubspot/calling-extensions-sdk/demo $ npm i
npm WARN prepublish-on-install As of npm@5, 'prepublish' scripts are deprecated.
npm WARN prepublish-on-install Use 'prepare' for build steps and 'prepublishOnly' for upload-only.
npm WARN prepublish-on-install See the deprecation note in 'npm help scripts' for more information.

> calling_framework@0.0.1 prepublish /some/path/node_modules/@hubspot/calling-extensions-sdk/demo
> npm run build

> calling_framework@0.0.1 build /some/path/node_modules/@hubspot/calling-extensions-sdk/demo
> webpack

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: a73b6ad3df4d89f78a61
Version: webpack 4.32.1
Time: 28ms
Built at: 05/22/2019 10:29:00 AM

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in Entry module not found: Error: Can't resolve './src' in '/some/path/node_modules/@hubspot/calling-extensions-sdk/demo'

```
If you make a default webpack.config.js file with:
```
module.exports = {
    entry : "./index.js",
}
```
It succeeds and you get a dist library with a main.js file.
Next problem then is, when running http-serve and opening the demopage, the html file tries to include a script with this line: 
`<script src="./build/index_combined.js" async=""></script>`
- the build folder and the index_comined.js file doesn't exist.
Maybe it should be ./dist/main.js  instead?

**Comment by HarminderSingh1** [comment]
@andersiversen - we filter out the webpack.config.js from the NPM package.  I wasn't expecting devs to be running the demo from the NPM.  We can add that webpack.config to the NPM package if that helps.  In the meantime, you should be able to run the demo by cloning the repo and running it from the demo folder of the repo.

**Comment by andersiversen** [comment]
It's fine, I just cloned the repo to the demo folder as you suggested - thank you.
