### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by taf2** [HubSpot/calling-extensions-sdk#99]
```
 npm start

> calling-extensions-sdk-demo@0.0.1 start
> node scripts/support_node_17+.js webpack-dev-server --open

Running on Node.js v19.8.1.
Setting --openssl-legacy-provider to support Node.js v17+.
node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by alonso-cadenas** [comment]
Hi @taf2, apologies for the inconvenience! We are looking to release a new version of the demo app in the upcoming weeks. In the meantime, you can do one of the following as a workaround:
1. Install Node.js v16 on your machine and go through [the installation steps](https://github.com/HubSpot/calling-extensions-sdk#installation) again.
2. [Set the --openssl-legacy-provider manually](https://weekendprojects.dev/posts/fixed-node-err_ossl_evp_unsupported/#1-using-the-openssl-legacy-provider-flag).
If you're still having issues, please use [our bug template](https://github.com/HubSpot/calling-extensions-sdk/issues/new?assignees=&labels=bug&template=bug-report.md&title=) so we can help!
